[commands]
update = "git pull && git submodule update --init"
build = [
  """cmake -GNinja %{trace '-DDISASSEMBLE=ON -DTRACE=ON'} \
  -DCMAKE_BUILD_TYPE=%{target} \
  --build build/%{target}""",
  "ninja -C build/%{target}"
]
run = "./build/%{target}/src/client/Client"
test = "cd build/%{target}/src/tests && ctest && cd ../../../.."

[params.target]
shortcut = "t"
description = "Define the application build target."
type = ["debug", "release", "profile", "trace"]
default = "debug"

[params.trace]
shortcut = "t"
description = "Activate tracing support."
type = "boolean"
