[commands]

[commands.update]
script = "git pull"
description = "Update repository code."

[commands.build]
script = [
  """cmake -GNinja %{trace '-DDISASSEMBLE=ON -DTRACE=ON'} \
  %{nolog '-DDEACTIVATE_LOGGING=ON'} \
  %{debug '-DDEBUG=ON'} \
  %{profile '-DPROFILE=ON'} \
  %{release '-DRELEASE=ON'} \
  -DCMAKE_BUILD_TYPE=%{target} \
  -B build/%{target}""",
  "ninja -C build/%{target}"
]
description = "Build the application for a given traget."

[commands.test]
script = "cd build/%{target}/src/tests && CTEST_OUTPUT_ON_FAILURE=TRUE ctest && cd ../../../.."
description = "Run all unit tests defined under src/tests"

[commands.release.brew]
script = "./scripts/release.sh"
description = "Build a production release for Homebrew on macOS."

[commands.format]
script = "find src -iname *.hpp -o -iname *.cpp | xargs clang-format -i"
description = "Format project sources via clang-format."

[params.target]
shortcut = "t"
description = "Define the application build target."
type = ["debug", "release"]
default = "debug"

[params.trace]
shortcut = "r"
description = "Activate tracing support and parser disassemble output."
type = "boolean"

[params.nolog]
shortcut = "l"
description = "Deactivate all logging output."
type = "boolean"

# @todo: The following 3 params can be removed after https://github.com/krieselreihe/litr/issues/51

[params.debug]
shortcut = "d"
description = "Set debug mode, even if build type differs."
type = "boolean"

[params.profile]
shortcut = "p"
description = "Build the application with profiling tools enabled."
type = "boolean"

[params.release]
description = "Create a release build detached from build target."
type = "boolean"
